### PR TITLE
Merge Developer's Commits and Reapply Own Changes

### LINKED ISSUE #6: Restore commit history and resolve disassociated repositories
This repository https://github.com/sugarlabs/mastermind-activity was built from a bundle.

The developer's original repository is here instead https://github.com/cristian99garcia/mastermind-activity

### PR DESCRIPTION
**Pull request by ghost**
- This pull request merges commits from the developer's repository into ours.
- Our repository initially branched off from the developer's repository at commit number 26.
- After that point, our repository diverged to address porting and bug fixes.
- The developer's original repository made only one additional commit, adding a difficulty level feature.
- If desired, we can create another pull request to incorporate this feature, giving credit to the author in the commit message.

This closes https://github.com/sugarlabs/mastermind-activity/issues/6.
KIndly review @walterbender @chimosky @quozl .

### CODE REVIEW

**Comment by chimosky** [comment]
The developer repo contains 27 commits and if you add the five commits here - minus the first which is where it was built from a bundle - that's 32 commits in total and your branch has 38 commits with some of them being a duplicate of what's already in this repo, and some reverts which I don't understand why.

You've also tampered with the committer in the git history, you're now the committer and not the original committer - you can change this with `git commit --amend` but you might not need to -.

I'll suggest you use the original repo as a base and then pull in the master branch here, create another branch and then cherry-pick the five commits here onto the 27 from the original, that way you'd retain the git history too and keep the commits to what's needed.

**Comment by ghost** [comment]
Yes I tried that we have diverted from developers repo at some point I thought it was commit 26 but it turns it might not be true it will take hours to resolve as we have done progress in our repo, thats why I tried the opposite way but yes it might not make sense to do the way I tried.
Thanks.

**Comment by quozl** [comment]
It is important to keep the original commits as much as possible, especially authorship.  If we can rebase our commits instead, that would be more appropriate.

Have we submitted our work upstream?

**Comment by ghost** [comment]
> The developer repo contains 27 commits and if you add the five commits here - minus the first which is where it was built from a bundle - that's 32 commits in total and your branch has 38 commits with some of them being a duplicate of what's already in this repo, and some reverts which I don't understand why.
> 
> You've also tampered with the committer in the git history, you're now the committer and not the original committer - you can change this with `git commit --amend` but you might not need to -.
> 
> I'll suggest you use the original repo as a base and then pull in the master branch here, create another branch and then cherry-pick the five commits here onto the 27 from the original, that way you'd retain the git history too and keep the commits to what's needed.

I tried it again so that all authors are intact without any tampering and the only tough part as I mentioned is resolving large amount of conflicts by hand.Maybe there may exist any easy way to do it.

**Comment by ghost** [comment]
> It is important to keep the original commits as much as possible, especially authorship. If we can rebase our commits instead, that would be more appropriate. Have we submitted our work upstream?

I think that is the major problem both the repo has become largely dissociated at some point but is it possible can you take a look at the first commit in our repo https://github.com/sugarlabs/mastermind-activity/commit/f0eeda74b498f9692a39d355fe49fc27bdba8aef this one how was it done , i mean to say what is the procedure by which activity is made from bundle.

**Comment by chimosky** [comment]
> I tried it again so that all authors are intact without any tampering and the only tough part as I mentioned is resolving large amount of conflicts by hand.Maybe there may exist any easy way to do it.

If you use the developer repo as your base repo, you'd only have to cherry-pick 5 commits which are the commits that exist in this repo besides the first one - the one where the activity was added from a bundle -.

What this would look like is;
```bash
$ git clone https://github.com/cvgarciarea/mastermind-activity.git
$ cd mastermind-activity
$ git remote add sugar-branch https://github.com/sugarlabs/mastermind-activity.git
$ git fetch sugar-branch master:sugar-master
# You'll do this for the five commits in this repo - excluding the first commit - 
$ git cherry-pick d02687f 
```

Hope this helps!

**Comment by ghost** [comment]
> > I tried it again so that all authors are intact without any tampering and the only tough part as I mentioned is resolving large amount of conflicts by hand.Maybe there may exist any easy way to do it.
> 
> If you use the developer repo as your base repo, you'd only have to cherry-pick 5 commits which are the commits that exist in this repo besides the first one - the one where the activity was added from a bundle -.
> 
> What this would look like is;
> 
> ```shell
> $ git clone https://github.com/cvgarciarea/mastermind-activity.git
> $ cd mastermind-activity
> $ git remote add sugar-branch https://github.com/sugarlabs/mastermind-activity.git
> $ git fetch sugar-branch master:sugar-master
> # You'll do this for the five commits in this repo - excluding the first commit - 
> $ git cherry-pick d02687f 
> ```
> 
> Hope this helps!

Large number of conflicts arised, thanks.

**Comment by chimosky** [comment]
I've made the changes, the conflicts I had to resolve were minimal, then I did a rebase from the developer's master to this master and then skipped every commit as I'd already cherry-picked the ones I needed. 
Hope this helps.

**Comment by ghost** [comment]
Thanks can you raise the PR I dont know what I am doing wrong.
I am getting 18 Merge conflicts almost in all the files.
All of them very large.

**Comment by chimosky** [comment]
> Thanks can you raise the PR I dont know what I am doing wrong. I am getting 18 Merge conflicts almost in all the files. All of them very large.

 I couldn't raise a PR because both repos don't have a common parent, hence I force pushed, but this is basically what I did;
```bash
$ git clone https://github.com/cvgarciarea/mastermind-activity.git
$ cd mastermind-activity
$ git remote add sugar-branch https://github.com/sugarlabs/mastermind-activity.git
$ git fetch sugar-branch master:sugar-master
# You'll do this for the five commits in this repo - excluding the first commit - 
$ git cherry-pick d02687f  # there will be very minimal conflicts to resolve on one or two cherry-picks
$ git checkout sugar-master
$ git rebase master
# This is where you'll get the conflicts you're talking about,
# thankfully you don't have to worry about them as they mostly stem from
# the first commit in this repo which was v1, you don't need to worry about
# it because it was gotten from the bundle and whole point of this update
# is to have the history merged with the five new commits here.
$ git rebase --skip # skips the commit because we don't need it.
# you can just skip till the rebase is successful because we've cherry-picked the commits
# we need.
# I did this rebase because I had sugar-master tracking this repo and not the developer's
# so I could force push here.
$ git push sugar-branch sugar-master:master
``` 

Hope this helps!

**Pull request closed without merging**
